### ISSUE TITLE
Problema no chat IA

### ISSUE THREAD

**Issue by ribarski** [ErycMJ/Sistemas_Web_CFP#1]
![image](https://github.com/user-attachments/assets/34723b6b-e3ea-4c24-9fd8-81b09a316204)
![image](https://github.com/user-attachments/assets/028cf2ed-b7e3-44e0-ba30-6b7ffcf21d0a)

------------------Erro 404 NOTFOUND NO CHAT PERFORMACE

**Comment by ErycMJ** [comment]
Corrigido
